#!/bin/bash

#cd ../localblockdevice  && rm -f go.sum && go get  -u ./...  && go get  -u ./...  && go mod tidy 

echo "-- nixomosegotools"
cd ../nixomosegotools   && rm -f go.sum &&  go get  -u ./...  && go mod tidy 

echo "-- zosbd2goclient"
cd ../zosbd2goclient    && rm -f go.sum &&  go get  -u ./...  && go mod tidy 

echo "-- stree_v"
cd ../stree_v           && rm -f go.sum &&  go get  -u ./...  && go mod tidy 

echo "-- blockdevicelib"
cd ../blockdevicelib    && rm -f go.sum &&  go get  -u ./...  && go mod tidy 

echo "-- compressblockdevice"
cd ../compressblockdevice    && rm -f go.sum &&  go get  -u ./...  && go mod tidy 

echo "-- localblockdevice"
cd ../localblockdevice  && rm -f go.sum &&  go get  -u ./...  && go mod tidy 

echo "-- slookup_i"
cd ../slookup_i  && rm -f go.sum &&  go get  -u ./...  && go mod tidy 

